#!/bin/bash

echo "Starting to read database with CloudFormation"

source credentials.sh

stack=$STACK_NAME

echo DB identifier:
aws cloudformation describe-stack-resource --stack-name=$stack --logical-resource-id=MyDB | jq '.StackResourceDetail.PhysicalResourceId'

echo DB instance:
aws rds describe-db-instances --db-instance-identifier=$DB_IDENTIFIER

echo "Finished."
